### ISSUE TITLE
Prevent to add different reaction to a poll

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/Botanist#15] opened 2019-05-06 20:38 UTC
We can actually add many reactions to the same poll like on this picture : 
![image](https://user-images.githubusercontent.com/23219818/57253715-abe2b700-704f-11e9-8976-0b6a50b9b4ef.png)

So we can agree and disagree.

**Comment by s0lst1ce** [comment] 2019-05-06 20:40
The invalid tag means the issue isn't correctly formatted or can't be accepted which ain't the case so I'm removing it.

**Comment by s0lst1ce** [comment] 2019-05-08 01:02
This can't happen anymore as it was fixed in https://github.com/organic-bots/ForeBot/commit/c27683cf8859c63c480756581ee6eb35be1771b4

**Closed as completed by s0lst1ce** 2019-05-08 01:02 UTC
Labels: bug
